### ISSUE TITLE
How to scale wzoom to the rotated image?

### ISSUE THREAD

**Issue by IgorSerebryanskiy** [worka/vanilla-js-wheel-zoom#21]
Hello,

Probably it is not an issue. But could you please let me know how is it better to update wzoom parameters or object to use it for the rotated images? I mean that initially, the image is horizontal, like 800x600 px. Then I use css transform rotate style (interaction with the user) and the image becomes vertical, like 600x800 px. And then the wzoom doesn't work properly due to the size was changed. And what do I need to do to update wzoom? Does it make sense?

Thank you in advance.

Best regards,
Igor

**Comment by worka** [comment]
Hello,

Quick way "on the knee". Works pretty well 😉

```javascript
var degreeRotation = 0;

function rotateImage() {
    image.style.transform = image.style.transform.replace(/(^|\s)rotate\(\d+deg\)($|\s)/i, '') + ' rotate(' + degreeRotation + 'deg)';
}

var observer = new MutationObserver(function (mutations) {
    mutations.forEach(function () {
        rotateImage();
    });
});

observer.observe(image, { attributes: true, attributeFilter: [ 'style' ] });

rotateButton.addEventListener('click', function () {
    degreeRotation = degreeRotation < 270 ? degreeRotation + 90 : 0;

    rotateImage();
});
```

😊😊😊

**Comment by IgorSerebryanskiy** [comment]
Ok, thank you.

**Comment by worka** [comment]
Indeed there is such a problem. This is due to the fact that the image has a scale set when the plugin is initialized, and then we rotate the image without using the plugin. I have not yet found any adequate solution to this problem other than how to make the block in which the image is located square.

[Demo](https://worka.github.io/vanilla-js-wheel-zoom/demo-image-rotate.html)

**Comment by worka** [comment]
> There is a problem with your demo : when the image is vertical, the bottom and the top of the image are cropped. Is there a way to change the scale factor correctly ?

Indeed there is such a problem. This is due to the fact that the image has a scale set when the plugin is initialized, and then we rotate the image without using the plugin. I have not yet found any adequate solution to this problem other than how to make the block in which the image is located square.

[Demo](https://worka.github.io/vanilla-js-wheel-zoom/demo-image-rotate.html)
